fail_fast: true
repos:
  - repo: local
    hooks:
      - id: custom-commit-msg
        name: Validate commit message format
        entry: scripts/githooks/commit-msg
        language: system
        stages: [commit-msg]
